### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by abd3lraouf** [osamabmaq/TafqeetJ#2]
Hello Osama,

Thank you very much for that great library. 
But as you already know, One shouldn't type fresh legacy code. As any code written without tests is considered legacy.

Please add unit tests to the library.

I can help with publishing the library on maven.

**Comment by osamabmaq** [comment]
Hello AbdElraouf,
I'm planning on adding tests in the coming days, thank you for this note.
And about Maven, I will publish it there directly after adding tests.

Thank you for your care.

**Comment by abd3lraouf** [comment]
You are welcome @osamabmaq

**Comment by osamabmaq** [comment]
Unit tests has been added.
And the library is now published on Maven central.
